# Generated by Django 5.1.1 on 2024-10-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="upload/product/"),
        ),
    ]
